 project/packet_recordee.lua
 project/samp-master/client/game/vehicle.cpp
 project/samp-master/client/game/vehicle.h
 project/samp-master/client/gui/common.h
 project/samp-master/client/gui/font.cpp
 project/samp-master/client/gui/font.h
 project/samp-master/client/gui/fontmanager.cpp
 project/samp-master/client/gui/fontmanager.h
 project/samp-master/client/gui/renderable.h
 project/samp-master/client/gui/resource.h
 project/samp-master/client/gui/stateblockmanager.cpp
 project/samp-master/client/gui/stateblockmanager.h
 project/samp-master/client/gui/textbuffer.cpp
 project/samp-master/client/gui/textbuffer.h
 project/samp-master/client/gui/textbufferbase.cpp
 project/samp-master/client/gui/textbufferbase.h
 project/samp-master/client/gui/texture.cpp
 project/samp-master/client/gui/texture.h
 project/samp-master/client/helpdialog.cpp
 project/samp-master/client/helpdialog.h
 project/samp-master/client/label.cpp
 project/samp-master/client/label.h
 project/samp-master/client/main.cpp
 project/samp-master/client/main.h
 project/samp-master/client/md5.cpp
 project/samp-master/client/md5.h
 project/samp-master/client/memorymodule/MemoryModule.c
 project/samp-master/client/memorymodule/MemoryModule.h
 project/samp-master/client/net/actorpool.cpp
 project/samp-master/client/net/actorpool.h
 project/samp-master/client/net/gangzonepool.cpp
 project/samp-master/client/net/gangzonepool.h
 project/samp-master/client/net/localplayer.cpp
 project/samp-master/client/net/localplayer.h
 project/samp-master/client/net/menupool.cpp
 project/samp-master/client/net/menupool.h
 project/samp-master/client/net/netgame.cpp
 project/samp-master/client/net/netgame.h
 project/samp-master/client/net/netrpc.cpp
 project/samp-master/client/net/netrpc.h
 project/samp-master/client/net/objectpool.cpp
 project/samp-master/client/net/objectpool.h
 project/samp-master/client/net/pickuppool.cpp
 project/samp-master/client/net/pickuppool.h
 project/samp-master/client/net/player_pool.h
 project/samp-master/client/net/playerpool.cpp
 project/samp-master/client/net/playerpool.h
 project/samp-master/client/net/remoteactor.cpp
 project/samp-master/client/net/remoteactor.h
 project/samp-master/client/net/remoteplayer.cpp
 project/samp-master/client/net/remoteplayer.h
 project/samp-master/client/net/scriptrpc.cpp
 project/samp-master/client/net/scriptrpc.h
 project/samp-master/client/net/textdrawpool.cpp
 project/samp-master/client/net/textdrawpool.h
 project/samp-master/client/net/vehiclepool.cpp
 project/samp-master/client/net/vehiclepool.h
 project/samp-master/client/netstats.cpp
 project/samp-master/client/netstats.h
 project/samp-master/client/newplayertags.cpp
 project/samp-master/client/newplayertags.h
 project/samp-master/client/outputdebugstring.h
 project/samp-master/client/playertags.cpp
 project/samp-master/client/playertags.h
 project/samp-master/client/resource.h
 project/samp-master/client/runutil.cpp
 project/samp-master/client/runutil.h
 project/samp-master/client/scoreboard.cpp
 project/samp-master/client/scoreboard.h
 project/samp-master/client/spawnscreen.cpp
 project/samp-master/client/spawnscreen.h
 project/samp-master/client/subclass.cpp
 project/samp-master/client/svrnetstats.cpp
 project/samp-master/client/svrnetstats.h
 project/samp-master/raknet/AsynchronousFileIO.cpp
 project/samp-master/raknet/AsynchronousFileIO.h
 project/samp-master/raknet/AutopatcherPatchContext.h
 project/samp-master/raknet/AutopatcherRepositoryInterface.h
 project/samp-master/raknet/BigTypes.h
 project/samp-master/raknet/BitStream.cpp
 project/samp-master/raknet/BitStream.h
 project/samp-master/raknet/BitStream_NoTemplate.cpp
 project/samp-master/raknet/BitStream_NoTemplate.h
 project/samp-master/raknet/CheckSum.cpp
 project/samp-master/raknet/CheckSum.h
 project/samp-master/raknet/ClientContextStruct.h
 project/samp-master/raknet/CommandParserInterface.cpp
 project/samp-master/raknet/CommandParserInterface.h
 project/samp-master/raknet/ConsoleServer.cpp
 project/samp-master/raknet/ConsoleServer.h
 project/samp-master/raknet/DS_BPlusTree.h
 project/samp-master/raknet/DS_BinarySearchTree.h
 project/samp-master/raknet/DS_ByteQueue.cpp
 project/samp-master/raknet/DS_ByteQueue.h
 project/samp-master/raknet/DS_Heap.h
 project/samp-master/raknet/DS_HuffmanEncodingTree.cpp
 project/samp-master/raknet/DS_HuffmanEncodingTree.h
 project/samp-master/raknet/DS_HuffmanEncodingTreeFactory.h
 project/samp-master/raknet/DS_HuffmanEncodingTreeNode.h
 project/samp-master/raknet/DS_LinkedList.h
 project/samp-master/raknet/DS_List.h
 project/samp-master/raknet/DS_Map.h
 project/samp-master/raknet/DS_MemoryPool.h
 project/samp-master/raknet/DS_OrderedChannelHeap.h
 project/samp-master/raknet/DS_OrderedList.h
 project/samp-master/raknet/DS_Queue.h
 project/samp-master/raknet/DS_QueueLinkedList.h
 project/samp-master/raknet/DS_RangeList.h
 project/samp-master/raknet/DS_Table.cpp
 project/samp-master/raknet/DS_Table.h
 project/samp-master/raknet/DS_Tree.h
 project/samp-master/raknet/DS_WeightedGraph.h
 project/samp-master/raknet/DataBlockEncryptor.cpp
 project/samp-master/raknet/DataBlockEncryptor.h
 project/samp-master/raknet/DataCompressor.cpp
 project/samp-master/raknet/DataCompressor.h
 project/samp-master/raknet/EmailSender.cpp
 project/samp-master/raknet/EmailSender.h
 project/samp-master/raknet/EncodeClassName.cpp
 project/samp-master/raknet/Export.h
 project/samp-master/raknet/ExtendedOverlappedPool.cpp
 project/samp-master/raknet/ExtendedOverlappedPool.h
 project/samp-master/raknet/FileOperations.cpp
 project/samp-master/raknet/FileOperations.h
 project/samp-master/raknet/FullyConnectedMesh.cpp
 project/samp-master/raknet/FullyConnectedMesh.h
 project/samp-master/raknet/GetTime.cpp
 project/samp-master/raknet/GetTime.h
 project/samp-master/raknet/InternalPacket.h
 project/samp-master/raknet/InternalPacketPool.cpp
 project/samp-master/raknet/InternalPacketPool.h
 project/samp-master/raknet/LinuxStrings.cpp
 project/samp-master/raknet/LinuxStrings.h
 project/samp-master/raknet/LogCommandParser.cpp
 project/samp-master/raknet/LogCommandParser.h
 project/samp-master/raknet/MTUSize.h
 project/samp-master/raknet/NetworkIDGenerator.cpp
 project/samp-master/raknet/NetworkIDGenerator.h
 project/samp-master/raknet/NetworkTypes.cpp
 project/samp-master/raknet/NetworkTypes.h
 project/samp-master/raknet/PacketEnumerations.h
 project/samp-master/raknet/PacketPool.h
 project/samp-master/raknet/PacketPriority.h
 project/samp-master/raknet/PluginInterface.cpp
 project/samp-master/raknet/RPCMap.cpp
 project/samp-master/raknet/PluginInterface.h
 project/samp-master/raknet/RPCMap.h
 project/samp-master/raknet/RPCNode.h
 project/samp-master/raknet/RSACrypt.h
 project/samp-master/raknet/RakAssert.h
 project/samp-master/raknet/RakClient.cpp
 project/samp-master/raknet/RakClient.h
 project/samp-master/raknet/RakClientInterface.h
 project/samp-master/raknet/RakNetCommandParser.cpp
 project/samp-master/raknet/RakNetCommandParser.h
 project/samp-master/raknet/RakNetDefines.h
 project/samp-master/raknet/RakNetStatistics.cpp
 project/samp-master/raknet/RakNetStatistics.h
 project/samp-master/raknet/RakNetworkFactory.cpp
 project/samp-master/raknet/RakNetworkFactory.h
 project/samp-master/raknet/RakPeer.cpp
 project/samp-master/raknet/RakServer.h
 project/samp-master/raknet/RakSleep.cpp
 project/samp-master/raknet/RakSleep.h
 project/samp-master/raknet/Rand.cpp
 project/samp-master/raknet/Rand.h
 project/samp-master/raknet/ReliabilityLayer.cpp
 project/samp-master/raknet/ReliabilityLayer.h
 project/samp-master/raknet/Replica.h
 project/samp-master/raknet/ReplicaEnums.h
 project/samp-master/raknet/RouterInterface.h
 project/samp-master/raknet/SAMP/SAMPRPC.cpp
 project/samp-master/raknet/SAMP/SAMPRPC.h
 project/samp-master/raknet/SAMP/SAMP_VER.h
 project/samp-master/raknet/SAMP/samp_auth.cpp
 project/samp-master/raknet/SAMP/samp_auth.h
 project/samp-master/raknet/SAMP/samp_netencr.cpp
 project/samp-master/raknet/SAMP/samp_netencr.h
 project/samp-master/raknet/SHA1.cpp
 project/samp-master/raknet/SHA1.h
 project/samp-master/raknet/SimpleMutex.cpp
 project/samp-master/raknet/SimpleMutex.h
 project/samp-master/raknet/SimpleTCPServer.h
 project/samp-master/raknet/SingleProducerConsumer.h
 project/samp-master/raknet/SocketLayer.cpp
 project/samp-master/raknet/SocketLayer.h
 project/samp-master/raknet/StringCompressor.cpp
 project/samp-master/raknet/StringCompressor.h
 project/samp-master/raknet/StringTable.cpp
 project/samp-master/raknet/StringTable.h
 project/samp-master/raknet/SystemAddressList.cpp
 project/samp-master/raknet/SystemDatabaseClient.cpp
 project/samp-master/raknet/SystemDatabaseClient.h
 project/samp-master/raknet/SystemDatabaseServer.cpp
 project/samp-master/raknet/SystemDatabaseServer.h
 project/samp-master/raknet/TCPInterface.cpp
 project/samp-master/raknet/TCPInterface.h
 project/samp-master/raknet/TableSerializer.cpp
 project/samp-master/raknet/TableSerializer.h
 project/samp-master/raknet/TelnetTransport.cpp
 project/samp-master/raknet/TelnetTransport.h
 project/samp-master/raknet/ThreadPool.h
 project/samp-master/raknet/TransportInterface.h
 project/samp-master/raknet/Types.h
 project/samp-master/raknet/_findfirst.cpp
 project/samp-master/raknet/_findfirst.h
 project/samp-master/raknet/multiplayer.h
 project/samp-master/raknet/rakpeer.h
 project/samp-master/raknet/rakpeerinterface.h
 project/samp-master/raknet/rakserver.cpp
 project/samp-master/raknet/rakserverinterface.h
 project/samp-master/raknet/rijndael-boxes.h
 project/samp-master/raknet/rijndael.cpp
 project/samp-master/raknet/rijndael.h
 project/samp-master/raknet/systemaddresslist.h
 project/samp-master/samp.sln
 project/samp-master/server/Makefile
 project/samp-master/server/amx/amx.c
 project/samp-master/server/amx/amx.h
 project/samp-master/server/amx/amxDGram.c
 project/samp-master/server/amx/amxcons.c
 project/samp-master/server/amx/amxcore.c
 project/samp-master/server/amx/amxdefn.asm
 project/samp-master/server/amx/amxexecn.asm
 project/samp-master/server/amx/amxfile.c
 project/samp-master/server/amx/amxfloat.c
 project/samp-master/server/amx/amxstring.c
 project/samp-master/server/amx/amxtime.c
 project/samp-master/server/amx/getch.c
 project/samp-master/server/amx/getch.h
 project/samp-master/server/amx/osdefs.h
 project/samp-master/server/amx/prefix.c
 project/samp-master/server/amx/prefix.h
 project/samp-master/server/amx/sclinux.h
 project/samp-master/server/console.cpp
 project/samp-master/server/console.h
 project/samp-master/server/exceptions.cpp
 project/samp-master/server/filterscripts.cpp
 project/samp-master/server/filterscripts.h
 project/samp-master/server/format.cpp
 project/samp-master/server/format.h
 project/samp-master/server/gamemodes.cpp
 project/samp-master/server/gamemodes.h
 project/samp-master/server/gangzonepool.cpp
 project/samp-master/server/gangzonepool.h
 project/samp-master/server/httpclient.cpp
 project/samp-master/server/httpclient.h
 project/samp-master/server/jenkinshash.h
 project/samp-master/server/main.cpp
 project/samp-master/server/main.h
 project/samp-master/server/menu.cpp
 project/samp-master/server/menu.h
 project/samp-master/server/menupool.cpp
 project/samp-master/server/menupool.h
 project/samp-master/server/netgame.cpp
 project/samp-master/server/netgame.h
 project/samp-master/server/netrpc.cpp
 project/samp-master/server/netrpc.h
 project/samp-master/server/object.cpp
 project/samp-master/server/object.h
 project/samp-master/server/objectpool.cpp
 project/samp-master/server/objectpool.h
 project/samp-master/server/pickuppool.cpp
 project/samp-master/server/pickuppool.h
 project/samp-master/server/player.cpp
 project/samp-master/server/player.h
 project/samp-master/server/playerpool.cpp
 project/samp-master/server/playerpool.h
 project/samp-master/server/plugincommon.h
 project/samp-master/server/plugininternal.h
 project/samp-master/server/pluginkey.h
 project/samp-master/server/plugins.cpp
 project/samp-master/server/plugins.h
 project/samp-master/server/query.cpp
 project/samp-master/server/rcon.cpp
 project/samp-master/server/rcon.h
 project/samp-master/server/rconrpc.cpp
 project/samp-master/server/rconrpc.h
 project/samp-master/server/runutil.cpp
 project/samp-master/server/runutil.h
 project/samp-master/server/scrcore.cpp
 project/samp-master/server/scrcustom.cpp
 project/samp-master/server/scrtimers.cpp
 project/samp-master/server/scrtimers.h
 project/samp-master/server/server.vcproj
 project/samp-master/server/server.vcxproj
 project/samp-master/server/server.vcxproj.filters
 project/samp-master/server/signer.cpp
 project/samp-master/server/signer.h
 project/samp-master/server/specialbuild.cpp
 project/samp-master/server/sqlite/sqlite3.c
 project/samp-master/server/sqlite/sqlite3.h
 project/samp-master/server/sqlite/sqlite_amx.c
 project/samp-master/server/system.h
 project/samp-master/server/textdrawpool.cpp
 project/samp-master/server/textdrawpool.h
 project/samp-master/server/vehicle.cpp
 project/samp-master/server/vehicle.h
 project/samp-master/server/vehiclepool.cpp
 project/samp-master/server/vehiclepool.h
 project/samp-master/server/vehmods.h
 project/samp-sch.zip
 project/armeabi-v7a/libcrashlytics.so
 project/armeabi-v7a/libchenh4x.so
 project/armeabi-v7a/libcrashlytics-handler.so
 project/armeabi-v7a/libImmEmulatorJ.so
 project/armeabi-v7a/libcrashlytics-common.so
 project/armeabi-v7a/libchensamp.so
 project/armeabi-v7a/libSCAnd.so
 project/armeabi-v7a/libTouchSenseSDK.so
 project/armeabi-v7a/libsamp.so
 project/armeabi-v7a/libcrashlytics-trampoline.so
 project/armeabi-v7a/libbass.so
 project/armeabi-v7a/libGTASA.so
 project/armeabi-v7a/libAML.so
 project/armeabi-v7a/libFastman92pluginLoader_ANDROID_ARM32.so
 project/armeabi-v7a/libpluginCleoExtender.so
 project/armeabi-v7a/libplugin_fastman92limitAdjuster_ANDROID_ARM32.so
 project/AudioCaptureSample-master/README.md
 project/AudioCaptureSample-master/app/build.gradle
 project/AudioCaptureSample-master/app/proguard-rules.pro
 project/AudioCaptureSample-master/app/src/androidTest/java/com/zynger/audiocapturesample/ExampleInstrumentedTest.kt
 project/AudioCaptureSample-master/app/src/main/AndroidManifest.xml
 project/AudioCaptureSample-master/app/src/main/java/com/zynger/audiocapturesample/AudioCaptureService.kt
 project/AudioCaptureSample-master/app/src/main/java/com/zynger/audiocapturesample/MainActivity.kt
 project/AudioCaptureSample-master/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
 project/AudioCaptureSample-master/app/src/main/res/drawable/ic_launcher_background.xml
 project/AudioCaptureSample-master/app/src/main/res/layout/activity_main.xml
 project/AudioCaptureSample-master/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
 project/AudioCaptureSample-master/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
 project/AudioCaptureSample-master/app/src/main/res/mipmap-hdpi/ic_launcher.png
 project/AudioCaptureSample-master/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
 project/AudioCaptureSample-master/app/src/main/res/mipmap-mdpi/ic_launcher.png
 project/AudioCaptureSample-master/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
 project/AudioCaptureSample-master/app/src/main/res/mipmap-xhdpi/ic_launcher.png
 project/AudioCaptureSample-master/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
 project/AudioCaptureSample-master/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
 project/AudioCaptureSample-master/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
 project/AudioCaptureSample-master/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
 project/AudioCaptureSample-master/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
 project/AudioCaptureSample-master/app/src/main/res/values/colors.xml
 project/AudioCaptureSample-master/app/src/main/res/values/strings.xml
 project/AudioCaptureSample-master/app/src/main/res/values/styles.xml
 project/AudioCaptureSample-master/app/src/test/java/com/zynger/audiocapturesample/ExampleUnitTest.kt
 project/AudioCaptureSample-master/build.gradle
 project/AudioCaptureSample-master/docs/app_screenshot.png
 project/AudioCaptureSample-master/docs/audio_waves.png
 project/AudioCaptureSample-master/gradle.properties
 project/AudioCaptureSample-master/gradle/wrapper/gradle-wrapper.jar
 project/AudioCaptureSample-master/gradle/wrapper/gradle-wrapper.properties
 project/AudioCaptureSample-master/gradlew
 project/AudioCaptureSample-master/gradlew.bat
 project/AudioCaptureSample-master/settings.gradle
 project/penambangmoonloader.lua/penambangmoon.lua
 project/samp/samp.unc.dat
 project/samp/samp.txt
 project/samp/samp.dxt.dat
 project/samp/samp.dxt.tmb
 project/samp/samp.dxt.toc
 project/samp/samp.etc.dat
 project/samp/samp.etc.tmb
 project/samp/samp.etc.toc
 project/samp/samp.pvr.dat
 project/samp/samp.pvr.tmb
 project/samp/samp.pvr.toc
 project/samp/samp.unc.tmb
 project/samp/samp.unc.toc
 project/server-status-main/release.json
 project/server-status-main/server.json
 project/server-status-main/status.json
 project/server-status-main/update.json
 project/txd/txd.360.dat
 project/txd/txd.360.tmb
 project/txd/txd.360.toc
 project/txd/txd.etc.dat
 project/txd/txd.etc.tmb
 project/txd/txd.etc.toc
 project/txd/txd.txt
 project/txd/txd.unc.tmb
